### PR TITLE
Gigfilliate Customers - Products - Variant Product

### PR DESCRIPTION
**Pull request by abdulrehmanali**

### CODE REVIEW

**Comment by justinestrada** [comment]
Damn you're a beast! That's a lot of code! 🔥 🔥 🔥

**Comment by justinestrada** [comment]
It looks like adding it to cart probably isn't adding the variation id, cause the cart is just showing Essentials Collection not the variations: https://watch.screencastify.com/v/rZqWq7al05uBHPWOMEIc

**Comment by abdulrehmanali** [comment]
> Damn you're a beast! That's a lot of code! 🔥 🔥 🔥

Thank you sir

**Comment by abdulrehmanali** [comment]
> It looks like adding it to cart probably isn't adding the variation id, cause the cart is just showing Essentials Collection not the variations: https://watch.screencastify.com/v/rZqWq7al05uBHPWOMEIc

That's weird let me check

**Comment by abdulrehmanali** [comment]
@justinestrada 
Screen Shot 2022-04-15 at 2 49 48 PM
It's working for me. I commented on the line where I am passing the variation. Also, check the console

**Pull request merged**
